@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjY3MzE1Mzh9.mKvTF1g__GRmCEaT8cXnrMOx6wIKOACc2sb9cyMLHSQ

### Posts Index
GET http://localhost:3000/posts.json

### Posts Create
POST http://localhost:3000/posts.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
"title": "New Blog Post",
"body": "This is a new test post that I am hoping is created successfully in my database so that I can later destory it for testing purposes",
"date": "2022-10-23",
"image": "https://m.media-amazon.com/images/I/91-Db4L6xjL.png"
}

### Posts Show
GET http://localhost:3000/posts/1.json

### Posts Update
PATCH http://localhost:3000/posts/3.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
"title": "Test authentication Post",
"body": "This is a test to check if the user authentication is working properly",
"image": "https://media.indiedb.com/images/games/1/78/77947/ss_ac25277f95e6dde71a5ddafd933edbd78.jpg"
}

### Posts Destroy
DELETE http://localhost:3000/posts/1.json
Authorization: Bearer {{jwt}}


### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}